package com.circulardollar.cdatm.constant;

public enum Errors {
  INVALID_COMMAND("INVALID_COMMAND"),
  UNSUPPORTED_COMMAND("UNSUPPORTED_COMMAND"),
  INVALID_LENGTH("INVALID_LENGTH"),
  EXCEEDS_MAX_LENGTH("EXCEEDS_MAX_LENGTH"),
  BELOW_MIN_LENGTH("BELOW_MIN_LENGTH"),
  INVALID_AMOUNT("INVALID_AMOUNT"),
  EXCEEDS_MAX_AMOUNT("EXCEEDS_MAX_AMOUNT"),
  EXCEEDS_BALANCE_AMOUNT("EXCEEDS_BALANCE_AMOUNT"),
  BELOW_MIN_AMOUNT("BELOW_MIN_AMOUNT"),
  UNSUPPORTED_API_VERSION("UNSUPPORTED_API_VERSION"),
  INTERRUPTED_EXCEPTION("INTERRUPTED_EXCEPTION"),
  REMOTE_RESPONSE_EXCEPTION("REMOTE_RESPONSE_EXCEPTION"),
  JSON_PARSE_EXCEPTION("JSON_PARSE_EXCEPTION"),
  IO_EXCEPTION("IO_EXCEPTION"),
  EXECUTION_EXCEPTION("EXECUTION_EXCEPTION"),
  XOR_ILLEGAL_EXCEPTION("XOR_ILLEGAL_EXCEPTION"),
  ILLEGAL_PARAMETER_EXCEPTION("ILLEGAL_PARAMETER_EXCEPTION"),
  INVALID_CARD_OR_PIN("INVALID_CARD_OR_PIN"),
  INVALID_TOKEN("INVALID_TOKEN"),
  MAX_BALANCE_REACHED("MAX_BALANCE_REACHED"),
  ZERO_BALANCE_REACHED("ZERO_BALANCE_REACHED");

  private final String value;

  Errors(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }
}
